version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
  server:
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    links:
      - mongodb
  client:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - server
